// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// i2s //
// --- //

#define i2s_wrap_target 0
#define i2s_wrap 9

static const uint16_t i2s_program_instructions[] = {
            //     .wrap_target
    0xb922, //  0: mov    x, y            side 1 [1] 
    0x7101, //  1: out    pins, 1         side 0 [1] 
    0x1941, //  2: jmp    x--, 1          side 1 [1] 
    0xf001, //  3: set    pins, 1         side 0     
    0x7001, //  4: out    pins, 1         side 0     
    0xb922, //  5: mov    x, y            side 1 [1] 
    0x7101, //  6: out    pins, 1         side 0 [1] 
    0x1946, //  7: jmp    x--, 6          side 1 [1] 
    0xf000, //  8: set    pins, 0         side 0     
    0x7001, //  9: out    pins, 1         side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_program = {
    .instructions = i2s_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_wrap_target, offset + i2s_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

