// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// SPDIF //
// ----- //

#define SPDIF_wrap_target 0
#define SPDIF_wrap 7

static const uint16_t SPDIF_program_instructions[] = {
            //     .wrap_target
    0x6021, //  0: out    x, 1                       
    0xa052, //  1: mov    y, ::y                     
    0xa002, //  2: mov    pins, y                    
    0x0027, //  3: jmp    !x, 7                      
    0xa052, //  4: mov    y, ::y                     
    0xa002, //  5: mov    pins, y                    
    0x0100, //  6: jmp    0                      [1] 
    0xa342, //  7: nop                           [3] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program SPDIF_program = {
    .instructions = SPDIF_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config SPDIF_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + SPDIF_wrap_target, offset + SPDIF_wrap);
    return c;
}
#endif

